/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of SVM.xs. Do not edit this file, edit SVM.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "SVM.xs"
#include <vector>
#include <map>

#ifdef __cplusplus
extern "C" {
#endif

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifdef __cplusplus
}
#endif

#include "bindings.h"
#include "libsvm.h"

DataSet *_new_dataset(double l) {

  return new DataSet(l);
}

SVM *_new_svm(int st, int kt, int d, double g, double c0, double C,
	      double nu, double e) {

  return new SVM(st, kt, d, g, c0, C, nu, e);
}

#line 40 "SVM.c"

XS(XS_Algorithm__SVM__DataSet__new_dataset); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__DataSet__new_dataset)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::DataSet::_new_dataset(l)");
    {
	double	l = (double)SvNV(ST(0));
	DataSet *	RETVAL;

	RETVAL = _new_dataset(l);
	ST(0) = sv_newmortal();
	if( RETVAL == NULL )	XSRETURN_UNDEF;
	sv_setref_pv( ST(0), "Algorithm::SVM::DataSet", (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__DataSet__getLabel); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__DataSet__getLabel)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::DataSet::_getLabel(THIS)");
    {
	DataSet *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM::DataSet") ) {
		THIS = (DataSet *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::DataSet::_getLabel() -- THIS is not an Algorithm::SVM::DataSet object" );
		XSRETURN_UNDEF;
	};
#line 39 "SVM.xs"
      RETVAL = THIS->getLabel();
#line 81 "SVM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__DataSet__setLabel); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__DataSet__setLabel)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::DataSet::_setLabel(THIS, l)");
    {
	double	l = (double)SvNV(ST(1));
	DataSet *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM::DataSet") ) {
		THIS = (DataSet *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::DataSet::_setLabel() -- THIS is not an Algorithm::SVM::DataSet object" );
		XSRETURN_UNDEF;
	};
#line 47 "SVM.xs"
      THIS->setLabel(l);
#line 106 "SVM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__SVM__DataSet__getAttribute); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__DataSet__getAttribute)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::DataSet::_getAttribute(THIS, k)");
    {
	int	k = (int)SvIV(ST(1));
	DataSet *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM::DataSet") ) {
		THIS = (DataSet *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::DataSet::_getAttribute() -- THIS is not an Algorithm::SVM::DataSet object" );
		XSRETURN_UNDEF;
	};
#line 53 "SVM.xs"
      RETVAL = THIS->getAttribute(k);
#line 132 "SVM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__DataSet__setAttribute); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__DataSet__setAttribute)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::DataSet::_setAttribute(THIS, k, v)");
    {
	int	k = (int)SvIV(ST(1));
	double	v = (double)SvNV(ST(2));
	DataSet *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM::DataSet") ) {
		THIS = (DataSet *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::DataSet::_setAttribute() -- THIS is not an Algorithm::SVM::DataSet object" );
		XSRETURN_UNDEF;
	};
#line 62 "SVM.xs"
      THIS->setAttribute(k,v);
#line 158 "SVM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__SVM__DataSet__getIndexAt); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__DataSet__getIndexAt)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::DataSet::_getIndexAt(THIS, i)");
    {
	int	i = (int)SvIV(ST(1));
	DataSet *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM::DataSet") ) {
		THIS = (DataSet *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::DataSet::_getIndexAt() -- THIS is not an Algorithm::SVM::DataSet object" );
		XSRETURN_UNDEF;
	};
#line 68 "SVM.xs"
			RETVAL = THIS->getIndexAt(i);
#line 184 "SVM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__DataSet__getValueAt); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__DataSet__getValueAt)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::DataSet::_getValueAt(THIS, i)");
    {
	int	i = (int)SvIV(ST(1));
	DataSet *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM::DataSet") ) {
		THIS = (DataSet *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::DataSet::_getValueAt() -- THIS is not an Algorithm::SVM::DataSet object" );
		XSRETURN_UNDEF;
	};
#line 76 "SVM.xs"
			RETVAL = THIS->getValueAt(i);
#line 211 "SVM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__DataSet__getMaxI); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__DataSet__getMaxI)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::DataSet::_getMaxI(THIS)");
    {
	DataSet *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM::DataSet") ) {
		THIS = (DataSet *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::DataSet::_getMaxI() -- THIS is not an Algorithm::SVM::DataSet object" );
		XSRETURN_UNDEF;
	};
#line 83 "SVM.xs"
			RETVAL = THIS->getMaxI();
#line 237 "SVM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__DataSet_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__DataSet_DESTROY)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::DataSet::DESTROY(THIS)");
    {
	DataSet *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM::DataSet") ) {
		THIS = (DataSet *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::DataSet::DESTROY() -- THIS is not an Algorithm::SVM::DataSet object" );
		XSRETURN_UNDEF;
	};

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__SVM__new_svm); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__new_svm)
{
    dXSARGS;
    if (items != 8)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_new_svm(st, kt, d, g, c0, C, nu, e)");
    {
	int	st = (int)SvIV(ST(0));
	int	kt = (int)SvIV(ST(1));
	int	d = (int)SvIV(ST(2));
	double	g = (double)SvNV(ST(3));
	double	c0 = (double)SvNV(ST(4));
	double	C = (double)SvNV(ST(5));
	double	nu = (double)SvNV(ST(6));
	double	e = (double)SvNV(ST(7));
	SVM *	RETVAL;

	RETVAL = _new_svm(st, kt, d, g, c0, C, nu, e);
	ST(0) = sv_newmortal();
	if( RETVAL == NULL )	XSRETURN_UNDEF;
	sv_setref_pv( ST(0), "Algorithm::SVM", (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__addDataSet); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__addDataSet)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_addDataSet(THIS, ds)");
    {
	DataSet *	ds;
	SVM *	THIS;

	if( sv_isobject(ST(1)) && sv_isa(ST(1), "Algorithm::SVM::DataSet") ) {
		ds = (DataSet *)SvIV((SV*)SvRV( ST(1) ));
	} else {
		warn( "Algorithm::SVM::_addDataSet() -- ds is not an Algorithm::SVM::DataSet object" );
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_addDataSet() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 107 "SVM.xs"
      THIS->addDataSet(ds);
#line 318 "SVM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__SVM__clearDataSet); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__clearDataSet)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_clearDataSet(THIS)");
    {
	SVM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_clearDataSet() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 112 "SVM.xs"
      THIS->clearDataSet();
#line 341 "SVM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__SVM__train); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__train)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_train(THIS, retrain)");
    {
	int	retrain = (int)SvIV(ST(1));
	SVM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_train() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 118 "SVM.xs"
      RETVAL = THIS->train(retrain);
#line 367 "SVM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__crossValidate); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__crossValidate)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_crossValidate(THIS, nfolds)");
    {
	int	nfolds = (int)SvIV(ST(1));
	SVM *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_crossValidate() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 126 "SVM.xs"
      RETVAL = THIS->crossValidate(nfolds);
#line 394 "SVM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__predict_value); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__predict_value)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_predict_value(THIS, ds)");
    {
	DataSet *	ds;
	SVM *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(1)) && sv_isa(ST(1), "Algorithm::SVM::DataSet") ) {
		ds = (DataSet *)SvIV((SV*)SvRV( ST(1) ));
	} else {
		warn( "Algorithm::SVM::_predict_value() -- ds is not an Algorithm::SVM::DataSet object" );
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_predict_value() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 134 "SVM.xs"
      RETVAL = THIS->predict_value(ds);
#line 428 "SVM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__predict); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__predict)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_predict(THIS, ds)");
    {
	DataSet *	ds;
	SVM *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(1)) && sv_isa(ST(1), "Algorithm::SVM::DataSet") ) {
		ds = (DataSet *)SvIV((SV*)SvRV( ST(1) ));
	} else {
		warn( "Algorithm::SVM::_predict() -- ds is not an Algorithm::SVM::DataSet object" );
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_predict() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 142 "SVM.xs"
      RETVAL = THIS->predict(ds);
#line 462 "SVM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__saveModel); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__saveModel)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_saveModel(THIS, filename)");
    {
	char *	filename = (char *)SvPV_nolen(ST(1));
	SVM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_saveModel() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 150 "SVM.xs"
      RETVAL = THIS->saveModel(filename);
#line 489 "SVM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__loadModel); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__loadModel)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_loadModel(THIS, filename)");
    {
	char *	filename = (char *)SvPV_nolen(ST(1));
	SVM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_loadModel() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 158 "SVM.xs"
      RETVAL = THIS->loadModel(filename);
#line 516 "SVM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__getNRClass); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__getNRClass)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_getNRClass(THIS)");
    {
	SVM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_getNRClass() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 165 "SVM.xs"
      RETVAL = THIS->getNRClass();
#line 542 "SVM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__getLabels); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__getLabels)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_getLabels(THIS, classes)");
    SP -= items;
    {
	int	classes = (int)SvIV(ST(1));
	SVM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_getLabels() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 173 "SVM.xs"
     int i;
     int *labels;
     labels = new int[classes];
     if(THIS->getLabels(labels)) {
       for (i=0;i < classes; i++) {
	  XPUSHs(sv_2mortal(newSViv(labels[i])));
       }
     } else {
       XSRETURN_UNDEF;
     }
#line 577 "SVM.c"
	PUTBACK;
	return;
    }
}


XS(XS_Algorithm__SVM__getSVRProbability); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__getSVRProbability)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_getSVRProbability(THIS)");
    {
	SVM *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_getSVRProbability() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 187 "SVM.xs"
      RETVAL = THIS->getSVRProbability();
#line 603 "SVM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__checkProbabilityModel); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__checkProbabilityModel)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_checkProbabilityModel(THIS)");
    {
	SVM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_checkProbabilityModel() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 194 "SVM.xs"
      RETVAL = THIS->checkProbabilityModel();
#line 629 "SVM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__setSVMType); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__setSVMType)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_setSVMType(THIS, st)");
    {
	int	st = (int)SvIV(ST(1));
	SVM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_setSVMType() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 202 "SVM.xs"
      THIS->setSVMType(st);
#line 654 "SVM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__SVM__getSVMType); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__getSVMType)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_getSVMType(THIS)");
    {
	SVM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_getSVMType() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 207 "SVM.xs"
      RETVAL = THIS->getSVMType();
#line 679 "SVM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__setKernelType); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__setKernelType)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_setKernelType(THIS, kt)");
    {
	int	kt = (int)SvIV(ST(1));
	SVM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_setKernelType() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 215 "SVM.xs"
      THIS->setKernelType(kt);
#line 704 "SVM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__SVM__getKernelType); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__getKernelType)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_getKernelType(THIS)");
    {
	SVM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_getKernelType() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 220 "SVM.xs"
      RETVAL = THIS->getKernelType();
#line 729 "SVM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__setGamma); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__setGamma)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_setGamma(THIS, g)");
    {
	double	g = (double)SvNV(ST(1));
	SVM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_setGamma() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 228 "SVM.xs"
      THIS->setGamma(g);
#line 754 "SVM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__SVM__getGamma); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__getGamma)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_getGamma(THIS)");
    {
	SVM *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_getGamma() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 233 "SVM.xs"
      RETVAL = THIS->getGamma();
#line 779 "SVM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__setDegree); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__setDegree)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_setDegree(THIS, d)");
    {
	int	d = (int)SvIV(ST(1));
	SVM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_setDegree() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 241 "SVM.xs"
      THIS->setDegree(d);
#line 804 "SVM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__SVM__getDegree); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__getDegree)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_getDegree(THIS)");
    {
	SVM *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_getDegree() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 246 "SVM.xs"
      RETVAL = THIS->getDegree();
#line 829 "SVM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__setCoef0); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__setCoef0)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_setCoef0(THIS, c)");
    {
	double	c = (double)SvNV(ST(1));
	SVM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_setCoef0() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 254 "SVM.xs"
      THIS->setCoef0(c);
#line 854 "SVM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__SVM__getCoef0); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__getCoef0)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_getCoef0(THIS)");
    {
	SVM *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_getCoef0() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 259 "SVM.xs"
      RETVAL = THIS->getCoef0();
#line 879 "SVM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__setC); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__setC)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_setC(THIS, c)");
    {
	double	c = (double)SvNV(ST(1));
	SVM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_setC() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 267 "SVM.xs"
      THIS->setC(c);
#line 904 "SVM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__SVM__getC); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__getC)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_getC(THIS)");
    {
	SVM *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_getC() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 272 "SVM.xs"
      RETVAL = THIS->getC();
#line 929 "SVM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__setNu); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__setNu)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_setNu(THIS, n)");
    {
	double	n = (double)SvNV(ST(1));
	SVM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_setNu() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 280 "SVM.xs"
      THIS->setNu(n);
#line 954 "SVM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__SVM__getNu); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__getNu)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_getNu(THIS)");
    {
	SVM *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_getNu() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 285 "SVM.xs"
      RETVAL = THIS->getNu();
#line 979 "SVM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM__setEpsilon); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__setEpsilon)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_setEpsilon(THIS, e)");
    {
	double	e = (double)SvNV(ST(1));
	SVM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_setEpsilon() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 293 "SVM.xs"
      THIS->setEpsilon(e);
#line 1004 "SVM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__SVM__getEpsilon); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM__getEpsilon)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::_getEpsilon(THIS)");
    {
	SVM *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::_getEpsilon() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};
#line 298 "SVM.xs"
      RETVAL = THIS->getEpsilon();
#line 1029 "SVM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__SVM_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__SVM_DESTROY)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Algorithm::SVM::DESTROY(THIS)");
    {
	SVM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::SVM") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::SVM::DESTROY() -- THIS is not an Algorithm::SVM object" );
		XSRETURN_UNDEF;
	};

	delete THIS;
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Algorithm__SVM); /* prototype to pass -Wmissing-prototypes */
XS(boot_Algorithm__SVM)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Algorithm::SVM::DataSet::_new_dataset", XS_Algorithm__SVM__DataSet__new_dataset, file);
        newXS("Algorithm::SVM::DataSet::_getLabel", XS_Algorithm__SVM__DataSet__getLabel, file);
        newXS("Algorithm::SVM::DataSet::_setLabel", XS_Algorithm__SVM__DataSet__setLabel, file);
        newXS("Algorithm::SVM::DataSet::_getAttribute", XS_Algorithm__SVM__DataSet__getAttribute, file);
        newXS("Algorithm::SVM::DataSet::_setAttribute", XS_Algorithm__SVM__DataSet__setAttribute, file);
        newXS("Algorithm::SVM::DataSet::_getIndexAt", XS_Algorithm__SVM__DataSet__getIndexAt, file);
        newXS("Algorithm::SVM::DataSet::_getValueAt", XS_Algorithm__SVM__DataSet__getValueAt, file);
        newXS("Algorithm::SVM::DataSet::_getMaxI", XS_Algorithm__SVM__DataSet__getMaxI, file);
        newXS("Algorithm::SVM::DataSet::DESTROY", XS_Algorithm__SVM__DataSet_DESTROY, file);
        newXS("Algorithm::SVM::_new_svm", XS_Algorithm__SVM__new_svm, file);
        newXS("Algorithm::SVM::_addDataSet", XS_Algorithm__SVM__addDataSet, file);
        newXS("Algorithm::SVM::_clearDataSet", XS_Algorithm__SVM__clearDataSet, file);
        newXS("Algorithm::SVM::_train", XS_Algorithm__SVM__train, file);
        newXS("Algorithm::SVM::_crossValidate", XS_Algorithm__SVM__crossValidate, file);
        newXS("Algorithm::SVM::_predict_value", XS_Algorithm__SVM__predict_value, file);
        newXS("Algorithm::SVM::_predict", XS_Algorithm__SVM__predict, file);
        newXS("Algorithm::SVM::_saveModel", XS_Algorithm__SVM__saveModel, file);
        newXS("Algorithm::SVM::_loadModel", XS_Algorithm__SVM__loadModel, file);
        newXS("Algorithm::SVM::_getNRClass", XS_Algorithm__SVM__getNRClass, file);
        newXS("Algorithm::SVM::_getLabels", XS_Algorithm__SVM__getLabels, file);
        newXS("Algorithm::SVM::_getSVRProbability", XS_Algorithm__SVM__getSVRProbability, file);
        newXS("Algorithm::SVM::_checkProbabilityModel", XS_Algorithm__SVM__checkProbabilityModel, file);
        newXS("Algorithm::SVM::_setSVMType", XS_Algorithm__SVM__setSVMType, file);
        newXS("Algorithm::SVM::_getSVMType", XS_Algorithm__SVM__getSVMType, file);
        newXS("Algorithm::SVM::_setKernelType", XS_Algorithm__SVM__setKernelType, file);
        newXS("Algorithm::SVM::_getKernelType", XS_Algorithm__SVM__getKernelType, file);
        newXS("Algorithm::SVM::_setGamma", XS_Algorithm__SVM__setGamma, file);
        newXS("Algorithm::SVM::_getGamma", XS_Algorithm__SVM__getGamma, file);
        newXS("Algorithm::SVM::_setDegree", XS_Algorithm__SVM__setDegree, file);
        newXS("Algorithm::SVM::_getDegree", XS_Algorithm__SVM__getDegree, file);
        newXS("Algorithm::SVM::_setCoef0", XS_Algorithm__SVM__setCoef0, file);
        newXS("Algorithm::SVM::_getCoef0", XS_Algorithm__SVM__getCoef0, file);
        newXS("Algorithm::SVM::_setC", XS_Algorithm__SVM__setC, file);
        newXS("Algorithm::SVM::_getC", XS_Algorithm__SVM__getC, file);
        newXS("Algorithm::SVM::_setNu", XS_Algorithm__SVM__setNu, file);
        newXS("Algorithm::SVM::_getNu", XS_Algorithm__SVM__getNu, file);
        newXS("Algorithm::SVM::_setEpsilon", XS_Algorithm__SVM__setEpsilon, file);
        newXS("Algorithm::SVM::_getEpsilon", XS_Algorithm__SVM__getEpsilon, file);
        newXS("Algorithm::SVM::DESTROY", XS_Algorithm__SVM_DESTROY, file);
    XSRETURN_YES;
}

